### ISSUE TITLE
When will the complete code be released?

### ISSUE THREAD

**Issue by lintaishen** [DavisMeee/SurgSora#3]
Great work! When will the complete code be released?

**Comment by DavisMeee** [comment]
Hmmm, I think all the code has already been released. Have you caught any issues about this?

**Comment by lintaishen** [comment]
> Hmmm, I think all the code has already been released. Have you caught any issues about this?

When we run train_stage1.py, we encounter an ImportError：
ModuleNotFoundError: No module named 'train_utils.unimatch.unimatch'

<img width="1927" height="492" alt="Image" src="https://github.com/user-attachments/assets/1ff2127e-d93d-4424-9802-793a3e415793" />

**Comment by DavisMeee** [comment]
Fixed

**Comment by lintaishen** [comment]
> Fixed

Thank you very much—we'll try again.

**Comment by lintaishen** [comment]
We tried it out and found that we're still encountering import errors. Could you please update the relevant code again?

<img width="1827" height="469" alt="Image" src="https://github.com/user-attachments/assets/b7268928-0e12-46b1-83d1-98c62a90a4da" />

**Comment by DavisMeee** [comment]
> We tried it out and found that we're still encountering import errors. Could you please update the relevant code again?
> 
> <img alt="Image" width="1827" height="469" src="https://private-user-images.githubusercontent.com/238139404/521629246-b7268928-0e12-46b1-83d1-98c62a90a4da.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjQ3MjcyMTcsIm5iZiI6MTc2NDcyNjkxNywicGF0aCI6Ii8yMzgxMzk0MDQvNTIxNjI5MjQ2LWI3MjY4OTI4LTBlMTItNDZiMS04M2QxLTk4YzYyYTkwYTRkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIwM1QwMTU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2VlNTgyZDVjOGM3ZGVmNzZjZGM4NDM1OTY4ZjBkZGYyYjI1NzNhMzFlZTNhOWU3ZWFmOTg1ZWIyYThiYzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mSCRrFTqBThkgAWjDe9I2rnSMfU_pwiM_s4CUHjkiTA">

Thanks for pointing this out. I have uploaded the whole unimatch function this time.
